#    This file is part of the package "parapin".
#
#    The parapin package is free software; you can redistribute it
#    and/or modify it under the terms of the GNU Library General Public
#    License (LGPL) as published by the Free Software Foundation.
#
#    The parapin package is distributed in the hope that it will be
#    useful, but WITHOUT ANY WARRANTY; without even the implied
#    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Library General Public License for more details.
#
#    You should have received a copy of the GNU Library General Public
#    License along with parapin; if not, write to the Free
#    Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
#    02111-1307 USA
#
#
#    For futher information on the parapin package, please refer to the
#    project information hosted on Sourceforge --
#
#    http://sourceforge.net/projects/parapin/
#
#
#
# Parapin top-level Kbuild file, to drive subdir kbuild processing for modules
#
# Currently maintained by Al Hooton (al@hootons.org)
#
# $Id $
#

# This top-level kbuild makefile allows kbuild to start in the main
# directory, instead of us launching it at the subdirs directly.  By 
# doing this, kbuild knows about external symbols from all our modules and
# can determine that parapindriver is dependent on symbols from kparapin,
# thereby avoiding warnings at build time about undefined symbols.

obj-y := kparapin/ parapindriver/
